Add ytag script, improve tag script.

diff --git a/.local/bin/tag b/.local/bin/tag
--- a/.local/bin/tag
+++ b/.local/bin/tag
@@ -1,32 +1,35 @@
 #!/bin/sh
 
 while getopts "a:t:A:n:N:d:g:c:" o; do case "$o" in
-    a) artist="$OPTARG" ;;
-    t) title="$OPTARG" ;;
-    A) album="$OPTARG" ;;
-    n) track="$OPTARG" ;;
-    N) total="$OPTARG" ;;
-    d) date="$OPTARG" ;;
-    g) genre="$OPTARG" ;;
-    c) comment="$OPTARG" ;;
+    a) artist="${OPTARG}" ;;
+    t) title="${OPTARG}" ;;
+    A) album="${OPTARG}" ;;
+    n) track="${OPTARG}" ;;
+    N) total="${OPTARG}" ;;
+    d) date="${OPTARG}" ;;
+    g) genre="${OPTARG}" ;;
+    c) comment="${OPTARG}" ;;
+    *) echo "Invalid option: -$OPTARG\n" && exit 1 ;;
 esac done
 
 shift $((OPTIND-1))
 
 file="$1"
 
-[ -f "$file"] || echo "Provide file to tag, please" && exit 1
-[ -z "$artist"] && echo "Enter an artist." && read -r artist
-[ -z "$title"] && echo "Enter n title." && read -r title
-[ -z "$album"] && echo "Enter an album." && read -r album
-[ -z "$track"] && echo "Enter a track number." && read -r artist
-
 temp="/tmp/tag-$(date +%s)"
-cp "$file" "$temp" && ffmpeg -i "$temp" -map 0 -y -codec copy \
-	-metadata artist="$artist" \
-    -metadata title="$title" \
-	-metadata album="$album" \
-	-metadata track="${track}${total:+/"$total"}" \
-    ${date:+-metadata date="$date"} \
-	${genre:+-metadata genre="$genre"} \
-	${comment:+-metadata comment="$comment"} "$file" && rm -f "$temp"
+trap 'rm -f $temp' HUP INT QUIT TERM PWR EXIT
+
+[ ! -f "$file" ] && echo "Provide file to tag." && exit 1
+[ -z "$title" ] && echo "Enter a title." && read -r title
+[ -z "$artist" ] && echo "Enter an artist." && read -r artist
+[ -z "$album" ] && echo "Enter an album." && read -r album
+# [ -z "$track" ] && echo 'Enter a track number.' && read -r track
+
+cp -f "$file" "$temp" && ffmpeg -i "$temp" -y -codec copy -map 0 \
+    -metadata:s:0 title="$title" \
+    -metadata:s:0 album="$album" \
+    -metadata:s:0 artist="$artist" \
+    ${track:+-metadata:s:0 track="${track}${total:+/"$total"}"} \
+    ${date:+-metadata:s:0 date="$date"} \
+    ${genre:+-metadata:s:0 genre="$genre"} \
+    ${comment:+-metadata:s:0 comment="$comment"} "$file"
